version: '3.4'
services:
  delius-nomis-wiremock:
    container_name: delius-nomis-wiremock
    build:
      context: delius-nomis-wiremock
      dockerfile: Dockerfile
    ports:
      - "5000:5000"


