db:
  driver:
    class:
      name: org.hsqldb.jdbcDriver
  url: jdbc:hsqldb:mem:db

server:
  port: 5000

spring:
  jpa:
    open-in-view: false

dataset:
  size: ${DATASET_SIZE:30}

auth:
  host: ${AUTH_HOST}
  clientId: ${AUTH_CLIENT_ID}
  clientSecret: ${AUTH_CLIENT_SECRET}

prisonApi:
  host: ${PRISON_API_HOST}

prisonerSearchApi:
  host: ${PRISONER_SEARCH_API_HOST}

